apiVersion: v1
kind: Service
metadata:
  name: nginx-svs
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30000
  selector:
    app: nginx

